services:
  db:
    image: postgres:16-alpine
    container_name: achievements_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: achievements
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d achievements"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: achievements_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://app_user:app_password@db:5432/achievements
      APP_DEBUG: false
    #ports:
    #  - "8000:8000"
    command: >
      sh -c "
      uv run alembic upgrade head &&
      uv run python -m app.seed_demo_data &&
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  nginx:
    image: nginx:1.27-alpine
    container_name: achievements_nginx
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
